### PR TITLE
Improved payload parsing for Py2 / Py3

### LINKED ISSUE #7: Detection of multipart payloads is spotty with mixed py2 / py3
This goes sour with the new py2/py3 compatible WebDAV support from https://github.com/plone/plone.dexterity/pull/102.

https://github.com/plone/plone.rfc822/blob/528ceafd750aa13848a9020ab8a7debf1070c283/plone/rfc822/_utils.py#L249

### PR DESCRIPTION
**Pull request by Rotonen**
Spotted from https://github.com/plone/plone.dexterity/pull/102
Closes https://github.com/plone/plone.rfc822/issues/7

### CODE REVIEW

**Comment by Rotonen** [comment]
@jenkins-plone-org please run jobs

**Comment by Rotonen** [comment]
@jenkins-plone-org please run jobs

**Comment by Rotonen** [comment]
@jenkins-plone-org please run jobs

**Comment by Rotonen** [comment]
Oh, `mr.roboto` does not cancel the previous builds upon starting the new ones, nor track the previous attempts per build id, so some the older ones pinging back are treated as successes for the newer ones as a race condition.

Now I'll have to let this cool down until they all finish and then run them again.

FYI @gforcada

**Comment by Rotonen** [comment]
Now built together with: https://github.com/plone/plone.dexterity/pull/104

**Comment by Rotonen** [comment]
So this had an unported typecheck for checking if the payload is a single payload or a multipart payload:
https://github.com/plone/plone.rfc822/blob/528ceafd750aa13848a9020ab8a7debf1070c283/plone/rfc822/_utils.py#L248-L249

This caused the wrong solution to get merged into `plone.dexterity`:
https://github.com/plone/plone.dexterity/blob/69653a66a172436cab76b8871f8555172875f582/plone/dexterity/filerepresentation.py#L839-L840

**Comment by datakurre** [comment]
Nice. Why string_types and not binary_type?

**Comment by Rotonen** [comment]
@datakurre because you get a string passed in on Python 3, not bytes.

Whether or not this is correct, is to be verified - I'd also like to be on top of the expectation - does it want bytes or a string in?

If it wants bytes in on Python 3, something else somewhere else is still off and the type check here is wrong.

**Comment by datakurre** [comment]
@Rotonen That seems to be how it should work. On Python 2  `email.message.Message.get_payload` returns `str` for single payload and on Python 3 it also returns `str`.

**Review by datakurre — APPROVED** [review]

**Pull request merged**
