### PR TITLE
Complete overhaul for Python 2/3 compat

### PR DESCRIPTION
**Pull request by jensens**
Includes refactoring b/c too many code broke the DRY rule which duplicated all the fixes needed. 

This is now Plone 5.2 only. 

Plone 5.1 and down sits already on a 1.x branch.

### CODE REVIEW

**Comment by jensens** [comment]
Btw., if this works it can be merged. It has no dependencies to other packages changed.

**Comment by pbauer** [comment]
Nice. I'll look at it soon. It seems that there is still is a issue in constructMessageFromSchema or renderMessage. See `./bin/test -s plone.app.textfield -t marshaler.rst`

**Comment by jensens** [comment]
Other modules need fixes as well I suppose. Since fields in zope.schema changed from py2 nonunicode-strings to py3 Unicode text some tests need special handling.

**Comment by jensens** [comment]
see also 
- https://github.com/plone/plone.app.textfield/pull/29
- https://github.com/plone/plone.namedfile/pull/66

**Comment by jensens** [comment]
I run tests with 

```
https://github.com/plone/plone.rfc822/pull/6
https://github.com/plone/plone.namedfile/pull/66
```

**Comment by jensens** [comment]
Plip Py3 job in Plone 5.2 is down to 176 failures (from 180) with this PR. 

green   : 91.961%
failures: 1.877%
errors  : 3.327%
skipped : 2.836%

**Comment by jensens** [comment]
But PR job hangs, no idea whats going on there.

**Comment by jensens** [comment]
This needs also new ``plone.testing``/ ``plone.app.testing`` from most recent py3 branches.  I would really like those to be merged.

**Comment by jensens** [comment]
for PR testing 
```
https://github.com/plone/plone.rfc822/pull/6
https://github.com/plone/plone.namedfile/pull/66
https://github.com/plone/plone.testing/pull/50
https://github.com/plone/plone.app.testing/pull/49
```

- https://github.com/plone/plone.rfc822/pull/6
- https://github.com/plone/plone.namedfile/pull/66
- https://github.com/plone/plone.testing/pull/50
- https://github.com/plone/plone.app.testing/pull/49

**Pull request merged**
